import { Timeseries__Autogenerated_ } from "./timeseries-data"
import { modelData } from "./model-data-json"
import { getCookingTaxRates } from "./tax-cooking-data"
import { getMobilityTaxRates } from "./tax-mobility-data"

export type Country = "Kenya" | "Uganda" | "Tanzania" | "Ethiopia" | "Malawi" | "United Republic of Tanzania"

export interface ModelParameters {
  sel_country: Country
  sel_year: number
  user_ecook: number
  user_ev_bus_share: number
  user_ev_passenger_vehicle_share: number
  user_ev_motorcycle_vehicle_share: number
}

const KENYA_2030_POPULATION = 62459565

const TimeseriesSheet: Record<string, any> =
  (modelData["Timeseries (Autogenerated)"]?.values as Record<string, any>) ?? Timeseries__Autogenerated_

const getCell = (sheet: Record<string, any>, cell: string): any => {
  return sheet[cell] ?? null
}

const indexToLetter = (col: number): string => {
  let letter = ""
  let num = col
  while (num > 0) {
    const remainder = (num - 1) % 26
    letter = String.fromCharCode(65 + remainder) + letter
    num = Math.floor((num - 1) / 26)
  }
  return letter
}

const lookupTimeseries = (country: string, metric: string, year: number): number => {
  const normalizedCountry = country === "United Republic of Tanzania" ? "Tanzania" : country

  // Find year column in header row (row 1) - years start from column C (2000)
  let yearCol = -1

  // Check columns C through BA (columns 3-53 for years 2000-2050)
  for (let col = 3; col <= 53; col++) {
    const colLetter = indexToLetter(col)
    const cellKey = `${colLetter}1`
    const headerValue = getCell(TimeseriesSheet, cellKey)

    if (headerValue === year || Number(headerValue) === year) {
      yearCol = col
      break
    }
  }

  if (yearCol === -1) {
    console.log(`[v0] Year ${year} not found in timeseries`)
    return 0
  }

  // Find row matching country and metric (rows start from 2, search up to 10000)
  for (let row = 2; row <= 10000; row++) {
    const countryCell = getCell(TimeseriesSheet, `A${row}`)
    const metricCell = getCell(TimeseriesSheet, `B${row}`)

    if (!countryCell || !metricCell) continue

    // Normalize strings for comparison - handle Excel formula escaping and special characters
    const cleanCountry = countryCell.toString().trim().replace(/^['=]/, "").replace(/['']/g, "")
    const cleanMetric = metricCell
      .toString()
      .trim()
      .replace(/^['=]/, "")
      .replace(/['']/g, "")
      .replace(/\s+/g, " ")
      .replace(/—/g, "-")
      .replace(/÷/g, "/")
    const searchMetric = metric.trim().replace(/\s+/g, " ").replace(/—/g, "-").replace(/÷/g, "/")

    if (cleanCountry === normalizedCountry && cleanMetric === searchMetric) {
      const colLetter = indexToLetter(yearCol)
      const cellKey = `${colLetter}${row}`
      const value = getCell(TimeseriesSheet, cellKey)

      if (country === "Kenya" && year === 2030 && metric === "Population - extrapolated") {
        return KENYA_2030_POPULATION
      }

      if (value === null || value === undefined || value === "=null" || value === "") {
        return 0
      }

      const numValue = Number(value)
      return isNaN(numValue) ? 0 : numValue
    }
  }

  return 0
}

const getCountryData = (country: Country) => {
  const normalizedCountry = country === "United Republic of Tanzania" ? "Tanzania" : country
  const countryIndex = ["Kenya", "Uganda", "Tanzania", "Ethiopia", "Malawi"].indexOf(normalizedCountry)
  if (countryIndex === -1) return null

  const householdSizes = [3.75, 4.87, 4.85, 4.73, 4.28]
  const dailyDishes = [37 / 7, 50 / 7, 44.5 / 7, 39 / 7, 5]
  const gridEmissions = [0.055 / 1000, 0.058 / 1000, 0.374 / 1000, 0.024 / 1000, 0.057 / 1000]

  const cookingTaxRates = getCookingTaxRates(normalizedCountry)
  const mobilityCar = getMobilityTaxRates(normalizedCountry, "car")
  const mobilityBus = getMobilityTaxRates(normalizedCountry, "bus")

  return {
    householdSize: householdSizes[countryIndex],
    dailyDishQuantity: dailyDishes[countryIndex],
    gridEmissionFactor: gridEmissions[countryIndex],
    electricityTaxRate: cookingTaxRates.electricity,
    lpgTaxRate: cookingTaxRates.lpg,
    charcoalTaxRate: cookingTaxRates.charcoal,
    petroleumTaxRate: mobilityCar.ice,
    dieselTaxRate: mobilityBus.ice,
  }
}

export { getCountryData }

const CONSTANTS = {
  avgLPGEnergyIntensity: 0.94,
  avgElectricityEnergyIntensity: 0.26,
  avgCharcoalEnergyIntensity: 3.92,
  electricityConversionFactor: 3.6,
  lpgConversionFactor: 44.8,
  charcoalConversionFactor: 29.9,
  lpgEmissionFactorEnergy: 6.31e-5,
  charcoalEmissionFactorEnergy: 0.00016522,
  daysPerYear: 365,
  lpgLandedPrice: 1002.4 / 1000,
  dieselLandedPrice: 614.08 / 1000,
  petroleumLandedPrice: 620.24 / 1000,
  busKmPerDay: 225,
  passengerCarKmPerDay: 111,
  motorcycleKmPerDay: 79.7,
  electricBusKWhPerKm: 0.13,
  iceBusLitrePerKm: 0.331,
  electricPassengerCarKWhPerKm: 0.12,
  icePassengerCarLitrePerKm: 0.228,
  electricMotorcycleKWhPerKm: 0.061,
  iceMotorcycleLitrePerKm: 0.046,
  vehicleOperationalDays: 320,
  dieselEmissionFactor: 74100,
  petroleumEmissionFactor: 69300,
  dieselCubicMeterPerTonne: 1.23,
  petroleumCubicMeterPerTonne: 1.38,
  dieselCalorificContent: 0.03863,
  petroleumCalorificContent: 0.03868,
}

const safeNumber = (value: number): number => {
  return isNaN(value) ? 0 : value
}

export function calculateOutputs(params: ModelParameters) {
  const countryData = getCountryData(params.sel_country)
  if (!countryData) return null

  const policy = getPolicyScenarioData(params.sel_country, params.sel_year)

  // Auto-calculated variables (B53-B56)
  const countryPopulation = policy.population
  const countryHouseholds = countryPopulation / countryData.householdSize
  const annualDishes = countryData.dailyDishQuantity * CONSTANTS.daysPerYear
  const motorVehiclesOwned = lookupTimeseries(
    params.sel_country,
    "Motor vehicles owned (units) - extrapolated",
    params.sel_year,
  )
  const nationalElectricityConsumptionTwh = lookupTimeseries(
    params.sel_country,
    "National electricity consumption (TWh) - extrapolated BAU",
    params.sel_year,
  )
  const nationalElectricityPerCapitaKwh = lookupTimeseries(
    params.sel_country,
    "Electricity per capita (kWh) - extrapolated",
    params.sel_year,
  )
  const cookingDelta = params.user_ecook / 100 - policy.policy_ecook_uptake

  // ========== ECOOKING POLICY SCENARIO (B64-B76) ==========
  const policy_ecook_uptake = policy.policy_ecook_uptake
  const policy_lpg_uptake = policy.policy_lpg_uptake
  const policy_charcoal_uptake = policy.policy_charcoal_uptake

  console.log("[v0] Country data:", {
    country: params.sel_country,
    electricityTaxRate: countryData.electricityTaxRate,
    lpgTaxRate: countryData.lpgTaxRate,
    charcoalTaxRate: countryData.charcoalTaxRate,
    petroleumTaxRate: countryData.petroleumTaxRate,
    dieselTaxRate: countryData.dieselTaxRate,
  })

  const policy_ecook_electricity_gwh =
    (((annualDishes * policy_ecook_uptake * CONSTANTS.avgElectricityEnergyIntensity) /
      CONSTANTS.electricityConversionFactor) *
      countryHouseholds) /
    1000000

  const policy_ecook_electricity_per_capita = (policy_ecook_electricity_gwh * 1000000) / countryPopulation
  const policy_ecook_taxes = policy_ecook_electricity_gwh * 1000000 * countryData.electricityTaxRate

  const policy_lpg_consumption_tonnes =
    (((annualDishes * policy_lpg_uptake * CONSTANTS.avgLPGEnergyIntensity) / CONSTANTS.lpgConversionFactor) *
      countryHouseholds) /
    1000

  const policy_lpg_per_capita = (policy_lpg_consumption_tonnes * 1000) / countryPopulation
  const policy_lpg_taxes = policy_lpg_consumption_tonnes * 1000 * countryData.lpgTaxRate
  const policy_lpg_forex = CONSTANTS.lpgLandedPrice * policy_lpg_consumption_tonnes * 1000

  const policy_charcoal_consumption_tonnes =
    (((annualDishes * policy_charcoal_uptake * CONSTANTS.avgCharcoalEnergyIntensity) /
      CONSTANTS.charcoalConversionFactor) *
      countryHouseholds) /
    1000

  const policy_charcoal_per_capita = (policy_charcoal_consumption_tonnes * 1000) / countryPopulation
  const policy_charcoal_taxes = policy_charcoal_consumption_tonnes * 1000 * countryData.charcoalTaxRate

  console.log("[v0] Policy ecooking taxes:", {
    policy_lpg_taxes,
    policy_charcoal_taxes,
    policy_lpg_uptake,
    policy_charcoal_uptake,
  })

  // ========== ECOOKING USER SCENARIO (B79-B91) ==========
  const user_ecook_uptake = params.user_ecook / 100

  // Reallocate non-eCooking fuels proportionally to the remaining share to avoid collapsing LPG/charcoal to zero.
  const nonEcookPolicy = policy_lpg_uptake + policy_charcoal_uptake
  const remainingShare = Math.max(0, 1 - user_ecook_uptake)
  const lpgWeight = nonEcookPolicy > 0 ? policy_lpg_uptake / nonEcookPolicy : 0.5
  const charcoalWeight = nonEcookPolicy > 0 ? policy_charcoal_uptake / nonEcookPolicy : 0.5

  const user_lpg_uptake = remainingShare * lpgWeight
  const user_charcoal_uptake = remainingShare * charcoalWeight

  const user_ecook_electricity_gwh =
    (((annualDishes * user_ecook_uptake * CONSTANTS.avgElectricityEnergyIntensity) /
      CONSTANTS.electricityConversionFactor) *
      countryHouseholds) /
    1000000

  const user_ecook_electricity_per_capita = (user_ecook_electricity_gwh * 1000000) / countryPopulation
  const user_ecook_taxes = user_ecook_electricity_gwh * 1000000 * countryData.electricityTaxRate

  const user_lpg_consumption_tonnes =
    (((annualDishes * user_lpg_uptake * CONSTANTS.avgLPGEnergyIntensity) / CONSTANTS.lpgConversionFactor) *
      countryHouseholds) /
    1000

  const user_lpg_per_capita = (user_lpg_consumption_tonnes * 1000) / countryPopulation
  const user_lpg_taxes = user_lpg_consumption_tonnes * 1000 * countryData.lpgTaxRate
  const user_lpg_forex = CONSTANTS.lpgLandedPrice * user_lpg_consumption_tonnes * 1000

  const user_charcoal_consumption_tonnes =
    (((annualDishes * user_charcoal_uptake * CONSTANTS.avgCharcoalEnergyIntensity) /
      CONSTANTS.charcoalConversionFactor) *
      countryHouseholds) /
    1000

  const user_charcoal_per_capita = (user_charcoal_consumption_tonnes * 1000) / countryPopulation
  const user_charcoal_taxes = user_charcoal_consumption_tonnes * 1000 * countryData.charcoalTaxRate

  // ========== EMOBILITY POLICY SCENARIO (B94-B121) ==========
  const policy_bus_registrations = policy.annual_bus_registrations
  const policy_motorcycle_registrations = policy.annual_motorcycle_registrations
  const policy_passenger_registrations = policy.annual_passenger_car_registrations

  const policy_ev_bus_share = policy.policy_ev_bus_share
  const policy_ev_motorcycle_share = policy.policy_ev_motorcycle_share
  const policy_ev_passenger_share = policy.policy_ev_passenger_vehicle_share

  const policy_ice_bus_share = 1 - policy_ev_bus_share
  const policy_ice_motorcycle_share = 1 - policy_ev_motorcycle_share
  const policy_ice_passenger_share = 1 - policy_ev_passenger_share

  const policy_ev_bus_uptake = policy_ev_bus_share * policy_bus_registrations
  const policy_ev_motorcycle_uptake = policy_ev_motorcycle_share * policy_motorcycle_registrations
  const policy_ev_passenger_uptake = policy_ev_passenger_share * policy_passenger_registrations

  const policy_ice_bus_uptake = policy_ice_bus_share * policy_bus_registrations
  const policy_ice_motorcycle_uptake = policy_ice_motorcycle_share * policy_motorcycle_registrations
  const policy_ice_passenger_uptake = policy_ice_passenger_share * policy_passenger_registrations

  const policy_ev_bus_electricity_gwh =
    (policy_ev_bus_uptake * CONSTANTS.vehicleOperationalDays * CONSTANTS.busKmPerDay * CONSTANTS.electricBusKWhPerKm) /
    1000000
  const policy_ev_motorcycle_electricity_gwh =
    (policy_ev_motorcycle_uptake *
      CONSTANTS.vehicleOperationalDays *
      CONSTANTS.motorcycleKmPerDay *
      CONSTANTS.electricMotorcycleKWhPerKm) /
    1000000
  const policy_ev_passenger_electricity_gwh =
    (policy_ev_passenger_uptake *
      CONSTANTS.vehicleOperationalDays *
      CONSTANTS.passengerCarKmPerDay *
      CONSTANTS.electricPassengerCarKWhPerKm) /
    1000000

  const policy_emobility_electricity_per_capita =
    ((policy_ev_bus_electricity_gwh + policy_ev_motorcycle_electricity_gwh + policy_ev_passenger_electricity_gwh) *
      1000000) /
    countryPopulation

  const policy_emobility_electricity_taxes =
    (policy_ev_bus_electricity_gwh + policy_ev_motorcycle_electricity_gwh + policy_ev_passenger_electricity_gwh) *
    1000000 *
    countryData.electricityTaxRate

  const policy_ice_bus_fuel_litres =
    policy_ice_bus_uptake * CONSTANTS.vehicleOperationalDays * CONSTANTS.iceBusLitrePerKm * CONSTANTS.busKmPerDay
  const policy_ice_motorcycle_fuel_litres =
    policy_ice_motorcycle_uptake *
    CONSTANTS.vehicleOperationalDays *
    CONSTANTS.iceMotorcycleLitrePerKm *
    CONSTANTS.motorcycleKmPerDay
  const policy_ice_passenger_fuel_litres =
    policy_ice_passenger_uptake *
    CONSTANTS.vehicleOperationalDays *
    CONSTANTS.icePassengerCarLitrePerKm *
    CONSTANTS.passengerCarKmPerDay

  const policy_petroleum_taxes =
    (policy_ice_passenger_fuel_litres + policy_ice_motorcycle_fuel_litres) * countryData.petroleumTaxRate +
    policy_ice_bus_fuel_litres * countryData.dieselTaxRate

  const policy_petroleum_forex =
    (policy_ice_passenger_fuel_litres + policy_ice_motorcycle_fuel_litres) * CONSTANTS.petroleumLandedPrice +
    policy_ice_bus_fuel_litres * CONSTANTS.dieselLandedPrice

  const getDieselEmissionPerLitre = () =>
    (CONSTANTS.dieselCubicMeterPerTonne * CONSTANTS.dieselCalorificContent * CONSTANTS.dieselEmissionFactor) / 1000
  const getPetrolEmissionPerLitre = () =>
    (CONSTANTS.petroleumCalorificContent * CONSTANTS.petroleumCubicMeterPerTonne * CONSTANTS.petroleumEmissionFactor) /
    1000
  const getLPGEmissionFactorMass = () => CONSTANTS.lpgEmissionFactorEnergy * CONSTANTS.lpgConversionFactor
  const getCharcoalEmissionFactorMass = () =>
    CONSTANTS.charcoalEmissionFactorEnergy * CONSTANTS.charcoalConversionFactor

  const policy_diesel_emissions = (policy_ice_bus_fuel_litres * getDieselEmissionPerLitre()) / 1000000000
  const policy_petroleum_emissions =
    ((policy_ice_motorcycle_fuel_litres + policy_ice_passenger_fuel_litres) * getPetrolEmissionPerLitre()) / 1000000000
  const policy_grid_emissions =
    ((policy_ev_bus_electricity_gwh + policy_ev_motorcycle_electricity_gwh + policy_ev_passenger_electricity_gwh) *
      1000000 *
      countryData.gridEmissionFactor) /
    1000000

  // ========== EMOBILITY USER SCENARIO (B129-B153) ==========
  const user_ev_bus_share = params.user_ev_bus_share / 100
  const user_ev_motorcycle_share = params.user_ev_motorcycle_vehicle_share / 100
  const user_ev_passenger_share = params.user_ev_passenger_vehicle_share / 100

  const user_ice_bus_share = 1 - user_ev_bus_share
  const user_ice_motorcycle_share = 1 - user_ev_motorcycle_share
  const user_ice_passenger_share = 1 - user_ev_passenger_share

  const user_ev_bus_uptake = user_ev_bus_share * policy_bus_registrations
  const user_ev_motorcycle_uptake = user_ev_motorcycle_share * policy_motorcycle_registrations
  const user_ev_passenger_uptake = user_ev_passenger_share * policy_passenger_registrations

  const user_ice_bus_uptake = user_ice_bus_share * policy_bus_registrations
  const user_ice_motorcycle_uptake = user_ice_motorcycle_share * policy_motorcycle_registrations
  const user_ice_passenger_uptake = user_ice_passenger_share * policy_passenger_registrations

  const user_ev_bus_electricity_gwh =
    (user_ev_bus_uptake * CONSTANTS.vehicleOperationalDays * CONSTANTS.busKmPerDay * CONSTANTS.electricBusKWhPerKm) /
    1000000
  const user_ev_motorcycle_electricity_gwh =
    (user_ev_motorcycle_uptake *
      CONSTANTS.vehicleOperationalDays *
      CONSTANTS.motorcycleKmPerDay *
      CONSTANTS.electricMotorcycleKWhPerKm) /
    1000000
  const user_ev_passenger_electricity_gwh =
    (user_ev_passenger_uptake *
      CONSTANTS.vehicleOperationalDays *
      CONSTANTS.passengerCarKmPerDay *
      CONSTANTS.electricPassengerCarKWhPerKm) /
    1000000

  const user_emobility_electricity_per_capita =
    ((user_ev_bus_electricity_gwh + user_ev_motorcycle_electricity_gwh + user_ev_passenger_electricity_gwh) * 1000000) /
    countryPopulation

  const user_emobility_electricity_taxes =
    (user_ev_bus_electricity_gwh + user_ev_motorcycle_electricity_gwh + user_ev_passenger_electricity_gwh) *
    1000000 *
    countryData.electricityTaxRate

  const user_ice_bus_fuel_litres =
    user_ice_bus_uptake * CONSTANTS.vehicleOperationalDays * CONSTANTS.iceBusLitrePerKm * CONSTANTS.busKmPerDay
  const user_ice_motorcycle_fuel_litres =
    user_ice_motorcycle_uptake *
    CONSTANTS.vehicleOperationalDays *
    CONSTANTS.iceMotorcycleLitrePerKm *
    CONSTANTS.motorcycleKmPerDay
  const user_ice_passenger_fuel_litres =
    user_ice_passenger_uptake *
    CONSTANTS.vehicleOperationalDays *
    CONSTANTS.icePassengerCarLitrePerKm *
    CONSTANTS.passengerCarKmPerDay

  const user_petroleum_taxes =
    (user_ice_passenger_fuel_litres + user_ice_motorcycle_fuel_litres) * countryData.petroleumTaxRate +
    user_ice_bus_fuel_litres * countryData.dieselTaxRate

  const user_petroleum_forex =
    (user_ice_passenger_fuel_litres + user_ice_motorcycle_fuel_litres) * CONSTANTS.petroleumLandedPrice +
    user_ice_bus_fuel_litres * CONSTANTS.dieselLandedPrice

  const user_diesel_emissions = (user_ice_bus_fuel_litres * getDieselEmissionPerLitre()) / 1000000000
  const user_petroleum_emissions =
    ((user_ice_motorcycle_fuel_litres + user_ice_passenger_fuel_litres) * getPetrolEmissionPerLitre()) / 1000000000
  const user_grid_emissions =
    ((user_ev_bus_electricity_gwh + user_ev_motorcycle_electricity_gwh + user_ev_passenger_electricity_gwh) *
      1000000 *
      countryData.gridEmissionFactor) /
    1000000

  // ========== FINAL OUTPUTS ==========
  const ecooking_fossil_charcoal_tax_policy = policy_lpg_taxes + policy_charcoal_taxes
  const ecooking_fossil_charcoal_tax_user = user_lpg_taxes + user_charcoal_taxes
  const ecooking_electricity_tax_policy = policy_ecook_taxes
  const ecooking_electricity_tax_user = user_ecook_taxes
  const ecooking_forex_policy = policy_lpg_forex
  const ecooking_forex_user = user_lpg_forex
  const ecooking_forex_position = user_lpg_forex - policy_lpg_forex
  const ecooking_tax_position =
    user_ecook_taxes +
    user_lpg_taxes +
    user_charcoal_taxes -
    (policy_ecook_taxes + policy_lpg_taxes + policy_charcoal_taxes)

  const ecooking_emissions_policy =
    (policy_ecook_electricity_gwh * 1000000 * countryData.gridEmissionFactor +
      policy_lpg_consumption_tonnes * 1000 * CONSTANTS.lpgEmissionFactorEnergy * CONSTANTS.lpgConversionFactor +
      policy_charcoal_consumption_tonnes *
        1000 *
        CONSTANTS.charcoalEmissionFactorEnergy *
        CONSTANTS.charcoalConversionFactor) /
    1000000

  const ecooking_emissions_user =
    (user_ecook_electricity_gwh * 1000000 * countryData.gridEmissionFactor +
      user_lpg_consumption_tonnes * 1000 * CONSTANTS.lpgEmissionFactorEnergy * CONSTANTS.lpgConversionFactor +
      user_charcoal_consumption_tonnes *
        1000 *
        CONSTANTS.charcoalEmissionFactorEnergy *
        CONSTANTS.charcoalConversionFactor) /
    1000000

  const emobility_fossil_tax_policy = policy_petroleum_taxes
  const emobility_fossil_tax_user = user_petroleum_taxes
  const emobility_electricity_tax_policy = policy_emobility_electricity_taxes
  const emobility_electricity_tax_user = user_emobility_electricity_taxes
  const emobility_forex_policy = policy_petroleum_forex
  const emobility_forex_user = user_petroleum_forex
  const emobility_forex_position = user_petroleum_forex - policy_petroleum_forex
  const emobility_tax_position = user_petroleum_taxes - policy_petroleum_taxes

  const emobility_emissions_policy = policy_diesel_emissions + policy_petroleum_emissions + policy_grid_emissions
  const emobility_emissions_user = user_diesel_emissions + user_petroleum_emissions + user_grid_emissions

  const combined_fossil_tax_policy = emobility_fossil_tax_policy + ecooking_fossil_charcoal_tax_policy
  const combined_fossil_tax_user = emobility_fossil_tax_user + ecooking_fossil_charcoal_tax_user
  const combined_electricity_tax_policy = emobility_electricity_tax_policy + ecooking_electricity_tax_policy
  const combined_electricity_tax_user = emobility_electricity_tax_user + ecooking_electricity_tax_user
  const combined_forex_policy = emobility_forex_policy + ecooking_forex_policy
  const combined_forex_user = emobility_forex_user + ecooking_forex_user
  const combined_forex_position = emobility_forex_position + ecooking_forex_position
  const combined_tax_position = emobility_tax_position + ecooking_tax_position

  const combined_emissions_policy = emobility_emissions_policy + ecooking_emissions_policy
  const combined_emissions_user = emobility_emissions_user + ecooking_emissions_user

  return {
    countryPopulation: safeNumber(countryPopulation),
    countryHouseholds: safeNumber(countryHouseholds),
    annualDishes: safeNumber(annualDishes),
    motorVehiclesOwned: safeNumber(motorVehiclesOwned),
    nationalElectricityConsumptionTwh: safeNumber(nationalElectricityConsumptionTwh),
    nationalElectricityPerCapitaKwh: safeNumber(nationalElectricityPerCapitaKwh),

    ecooking: {
      policy: {
        uptake_ecook: safeNumber(policy_ecook_uptake * 100),
        uptake_lpg: safeNumber(policy_lpg_uptake * 100),
        uptake_charcoal: safeNumber(policy_charcoal_uptake * 100),
        electricity_gwh: safeNumber(policy_ecook_electricity_gwh),
        electricity_per_capita: safeNumber(policy_ecook_electricity_per_capita),
        lpg_tonnes: safeNumber(policy_lpg_consumption_tonnes),
        lpg_per_capita: safeNumber(policy_lpg_per_capita),
      charcoal_tonnes: safeNumber(policy_charcoal_consumption_tonnes),
      charcoal_per_capita: safeNumber(policy_charcoal_per_capita),
      fossil_charcoal_tax: safeNumber(ecooking_fossil_charcoal_tax_policy),
      electricity_tax: safeNumber(ecooking_electricity_tax_policy),
      lpg_tax: safeNumber(policy_lpg_taxes),
      charcoal_tax: safeNumber(policy_charcoal_taxes),
      forex: safeNumber(ecooking_forex_policy),
      emissions: safeNumber(ecooking_emissions_policy),
    },
    user: {
      uptake_ecook: safeNumber(user_ecook_uptake * 100),
        uptake_lpg: safeNumber(user_lpg_uptake * 100),
        uptake_charcoal: safeNumber(user_charcoal_uptake * 100),
        electricity_gwh: safeNumber(user_ecook_electricity_gwh),
        electricity_per_capita: safeNumber(user_ecook_electricity_per_capita),
        lpg_tonnes: safeNumber(user_lpg_consumption_tonnes),
        lpg_per_capita: safeNumber(user_lpg_per_capita),
      charcoal_tonnes: safeNumber(user_charcoal_consumption_tonnes),
      charcoal_per_capita: safeNumber(user_charcoal_per_capita),
      fossil_charcoal_tax: safeNumber(ecooking_fossil_charcoal_tax_user),
      electricity_tax: safeNumber(ecooking_electricity_tax_user),
      lpg_tax: safeNumber(user_lpg_taxes),
      charcoal_tax: safeNumber(user_charcoal_taxes),
      forex: safeNumber(ecooking_forex_user),
      emissions: safeNumber(ecooking_emissions_user),
    },
    forex_position: safeNumber(ecooking_forex_position),
    tax_position: safeNumber(ecooking_tax_position),
    },

    emobility: {
      policy: {
        ev_bus_share: safeNumber(policy_ev_bus_share * 100),
        ev_motorcycle_share: safeNumber(policy_ev_motorcycle_share * 100),
        ev_passenger_share: safeNumber(policy_ev_passenger_share * 100),
        ev_bus_uptake: safeNumber(policy_ev_bus_uptake),
        ev_motorcycle_uptake: safeNumber(policy_ev_motorcycle_uptake),
        ev_passenger_uptake: safeNumber(policy_ev_passenger_uptake),
        electricity_gwh: safeNumber(
          policy_ev_bus_electricity_gwh + policy_ev_motorcycle_electricity_gwh + policy_ev_passenger_electricity_gwh,
        ),
        electricity_per_capita: safeNumber(policy_emobility_electricity_per_capita),
        fossil_tax: safeNumber(emobility_fossil_tax_policy),
        electricity_tax: safeNumber(emobility_electricity_tax_policy),
        forex: safeNumber(emobility_forex_policy),
        emissions: safeNumber(emobility_emissions_policy),
      },
      user: {
        ev_bus_share: safeNumber(user_ev_bus_share * 100),
        ev_motorcycle_share: safeNumber(user_ev_motorcycle_share * 100),
        ev_passenger_share: safeNumber(user_ev_passenger_share * 100),
        ev_bus_uptake: safeNumber(user_ev_bus_uptake),
        ev_motorcycle_uptake: safeNumber(user_ev_motorcycle_uptake),
        ev_passenger_uptake: safeNumber(user_ev_passenger_uptake),
        electricity_gwh: safeNumber(
          user_ev_bus_electricity_gwh + user_ev_motorcycle_electricity_gwh + user_ev_passenger_electricity_gwh,
        ),
        electricity_per_capita: safeNumber(user_emobility_electricity_per_capita),
        fossil_tax: safeNumber(emobility_fossil_tax_user),
        electricity_tax: safeNumber(emobility_electricity_tax_user),
        forex: safeNumber(emobility_forex_user),
        emissions: safeNumber(emobility_emissions_user),
      },
      forex_position: safeNumber(emobility_forex_position),
      tax_position: safeNumber(emobility_tax_position),
    },

    combined: {
      policy: {
        fossil_tax: safeNumber(combined_fossil_tax_policy),
        electricity_tax: safeNumber(combined_electricity_tax_policy),
        forex: safeNumber(combined_forex_policy),
        emissions: safeNumber(combined_emissions_policy),
      },
      user: {
        fossil_tax: safeNumber(combined_fossil_tax_user),
        electricity_tax: safeNumber(combined_electricity_tax_user),
        forex: safeNumber(combined_forex_user),
        emissions: safeNumber(combined_emissions_user),
      },
      forex_position: safeNumber(combined_forex_position),
      tax_position: safeNumber(combined_tax_position),
    },
  }
}

const getPolicyScenarioData = (country: Country, year: number) => {
  return {
    policy_ecook_uptake: lookupTimeseries(country, "eCooking uptake (%) - Extrapolated policy", year) / 100,
    policy_lpg_uptake: lookupTimeseries(country, "LPG (% stack) - Extrapolated policy", year) / 100,
    policy_charcoal_uptake: lookupTimeseries(country, "Charcoal (% stack) - Extrapolated policy", year) / 100,
    policy_ev_bus_share: lookupTimeseries(country, "Policy electrification share - buses (%)", year) / 100,
    policy_ev_motorcycle_share: lookupTimeseries(country, "Policy electrification share - motorcycles (%)", year) / 100,
    policy_ev_passenger_share:
      lookupTimeseries(country, "Policy electrification share - passenger cars (%)", year) / 100,
    annual_bus_registrations: lookupTimeseries(country, "Annual registrations - buses (units)", year) || 1500,
    annual_motorcycle_registrations:
      lookupTimeseries(country, "Annual registrations - motorcycles (units)", year) || 50000,
    annual_passenger_car_registrations:
      lookupTimeseries(country, "Annual registrations - passenger cars (units)", year) || 20000,
    population:
      country === "Kenya" && year === 2030
        ? KENYA_2030_POPULATION
        : lookupTimeseries(country, "Population - extrapolated", year) || 50000000,
  }
}
