// Script to convert tab-separated timeseries data to Excel cell format
import { readFileSync, writeFileSync } from "fs"

// Read the raw data
const rawData = readFileSync("user_read_only_context/text_attachments/pasted-text-43E8r.txt", "utf-8")
const lines = rawData.split("\n").filter((line) => line.trim())

// Parse headers (year columns)
const headers = lines[0].split("\t")
const years = headers.slice(2).map((h) => Number.parseInt(h)) // Skip Country and Series columns

// Column letters mapping (A, B, C, ..., Z, AA, AB, etc.)
function getColumnLetter(index: number): string {
  let result = ""
  while (index >= 0) {
    result = String.fromCharCode(65 + (index % 26)) + result
    index = Math.floor(index / 26) - 1
  }
  return result
}

// Build Excel object
const excelData: Record<string, any> = {}

// Add header row
excelData["A1"] = "='Country'"
excelData["B1"] = "='Series'"
headers.slice(2).forEach((year, idx) => {
  const col = getColumnLetter(idx + 2)
  excelData[`${col}1`] = Number.parseInt(year)
})

// Parse data rows
let rowNum = 2
for (let i = 1; i < lines.length; i++) {
  const parts = lines[i].split("\t")
  if (parts.length < 3) continue

  const country = parts[0].trim()
  const series = parts[1].trim()
  const values = parts.slice(2)

  // Add country and series
  excelData[`A${rowNum}`] = `='${country}'`
  excelData[`B${rowNum}`] = `='${series}'`

  // Add values
  values.forEach((val, idx) => {
    const col = getColumnLetter(idx + 2)
    const cellKey = `${col}${rowNum}`

    // Handle empty values and numbers
    if (val === "" || val === "null" || val === "NULL") {
      excelData[cellKey] = "=null"
    } else {
      const num = Number.parseFloat(val)
      excelData[cellKey] = isNaN(num) ? `='${val}'` : num
    }
  })

  rowNum++
}

// Generate TypeScript file
const output = `// Auto-generated from Final_bayes_model_eCooking_eMobility_V3 - to json.xlsx
export const Timeseries__Autogenerated_ = ${JSON.stringify(excelData, null, 2)};
`

writeFileSync("lib/timeseries-data.ts", output)
console.log("[v0] Converted timeseries data successfully. Total rows:", rowNum - 1)
